# Generated by Django 5.2.9 on 2025-12-04 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('where', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yangilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qachon', models.DateField(auto_now_add=True)),
                ('desc', models.TextField()),
                ('categoy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yangilik.categoriy')),
            ],
        ),
    ]
