# Generated by Django 5.2.9 on 2025-12-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriy',
            name='where',
            field=models.DateField(),
        ),
    ]
